apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "recording.fullname" . }}
  labels:
    app: {{ template "recording.name" . }}
    chart: {{ template "recording.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "recording.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
      labels:
        app: {{ template "recording.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.recording.image.repository }}:{{ .Values.recording.image.tag }}"
          imagePullPolicy: {{ .Values.recording.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.recording.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          resources:
{{ toYaml .Values.recording.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}