{{- $serviceType := .Values.service.type -}}
apiVersion: v1
kind: Service
metadata:
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "basicapp.fullname" . }}
  labels:
    app: {{ template "basicapp.name" . }}
    chart: {{ template "basicapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ $serviceType }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
      {{- if eq $serviceType "NodePort" }}
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ template "basicapp.name" . }}
    release: {{ .Release.Name }}