apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "nuve.fullname" . }}
  labels:
    app: {{ template "nuve.name" . }}
    chart: {{ template "nuve.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "nuve.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- with .Values.hpa.metrics }}
  metrics:
{{ toYaml . | indent 4 }}
  {{- end }}